// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(MatchamkingContext))]
    partial class MatchamkingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("backend.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Goles")
                        .HasColumnType("int");

                    b.Property<bool>("Suplentes")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("backend.Models.Jugador", b =>
                {
                    b.Property<string>("Nickname")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CantRacha")
                        .HasColumnType("int");

                    b.Property<int>("Derrotas")
                        .HasColumnType("int");

                    b.Property<float>("Elo")
                        .HasColumnType("float");

                    b.Property<int>("Empates")
                        .HasColumnType("int");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("GolesAFavor")
                        .HasColumnType("int");

                    b.Property<int>("GolesEnContra")
                        .HasColumnType("int");

                    b.Property<int>("Jugados")
                        .HasColumnType("int");

                    b.Property<bool>("Resaca")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Victorias")
                        .HasColumnType("int");

                    b.HasKey("Nickname");

                    b.HasIndex("EquipoId");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("backend.Models.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cancha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GanadorId")
                        .HasColumnType("int");

                    b.Property<int>("PerdedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GanadorId");

                    b.HasIndex("PerdedorId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("JugadorPartido", b =>
                {
                    b.Property<string>("JugadoresNickname")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PartidosId")
                        .HasColumnType("int");

                    b.HasKey("JugadoresNickname", "PartidosId");

                    b.HasIndex("PartidosId");

                    b.ToTable("JugadorPartido");
                });

            modelBuilder.Entity("backend.Models.Jugador", b =>
                {
                    b.HasOne("backend.Models.Equipo", null)
                        .WithMany("Jugadores")
                        .HasForeignKey("EquipoId");
                });

            modelBuilder.Entity("backend.Models.Partido", b =>
                {
                    b.HasOne("backend.Models.Equipo", "Ganador")
                        .WithMany()
                        .HasForeignKey("GanadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Equipo", "Perdedor")
                        .WithMany()
                        .HasForeignKey("PerdedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ganador");

                    b.Navigation("Perdedor");
                });

            modelBuilder.Entity("JugadorPartido", b =>
                {
                    b.HasOne("backend.Models.Jugador", null)
                        .WithMany()
                        .HasForeignKey("JugadoresNickname")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Partido", null)
                        .WithMany()
                        .HasForeignKey("PartidosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Equipo", b =>
                {
                    b.Navigation("Jugadores");
                });
#pragma warning restore 612, 618
        }
    }
}
